name: Maven CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Maven build
        run: mvn --fail-fast --update-snapshots tidy:check license:check com.github.spotbugs:spotbugs-maven-plugin:check verify
